before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=1
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -X 'github.com/belphemur/mangal/constant.BuiltAt={{ .Date }}'
      - -X 'github.com/belphemur/mangal/constant.BuiltBy={{ .Env.USER }}'
      - -X 'github.com/belphemur/mangal/constant.Revision={{ .ShortCommit }}'
      - -s
      - -w
    ignore:
      - goos: windows
        goarch: arm64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      android: Android
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - completions/*
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  groups:
    - title: Dependency updates
      regexp: "^.*feat\\(deps\\)*:+.*$"
      order: 300
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 100
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 200
    - title: 'Documentation updates'
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 400
    - title: Other work
      order: 9999
  filters:
    exclude:
      - '^test'
      - '^chore'
      - '^refactor'
      - '^build'
      - 'merge conflict'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy

dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - "belphemur/mangal:latest"
    skip_push: false
    use: docker
release:
  github:
    owner: belphemur
    name: mangal

  name_template: "{{.ProjectName}} v{{.Version}}"
  header: |

    ## What's new?

  footer: |

    **Full Changelog**: https://github.com/belphemur/mangal/compare/{{ .PreviousTag }}...{{ .Tag }}

    ---

    Bugs? Suggestions? [Open an issue](https://github.com/belphemur/mangal/issues/new/choose)

nfpms:
  - file_name_template: "{{ .ConventionalFileName }}"
    homepage: https://github.com/belphemur/mangal
    maintainer: belphemur <mangal@aaflalo.me>
    description: |-
      The most advanced cli manga downloader in the entire universe!

    license: MIT
    formats:
      - deb
      - rpm

    bindir: /usr/local/bin
    section: utils

    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package

    contents:
      - src: ./completions/mangal.bash
        dst: /usr/share/bash-completion/completions/mangal
        file_info:
          mode: 0644
      - src: ./completions/mangal.fish
        dst: /usr/share/fish/completions/mangal.fish
        file_info:
          mode: 0644
      - src: ./completions/mangal.zsh
        dst: /usr/share/zsh/vendor-completions/_mangal
        file_info:
          mode: 0644
      - src: ./LICENSE
        dst: /usr/share/doc/mangal/copyright
        file_info:
          mode: 0644
