/*
MangaUpdates API

This API powers our website. Most API functions are public and do not require an account. For user-based functions, you must register an account. Currently, user registration must be done through our main website and is disabled via this API.  Download OpenAPI Specification: [openapi.yaml](openapi.yaml)  Please contact us at the following emails if you have questions:  * lambchopsil@mangaupdates.com * manick@mangaupdates.com  ## Warranties  MangaUpdates makes no warranties about service availability, correctness of the data, or anything else. The service is provided as is, and may change at any time.  ## Acceptable Use Policy  * You will credit MangaUpdates when using data provided by this API. * You will use reasonable spacing between requests so as not to overwhelm the MangaUpdates servers, and employ caching mechanisms when accessing data. * You will NOT use MangaUpdates data or API in a way that will:     * Deceive or defraud users     * Assist or perform an illegal action     * Create spam     * Damage the database  We reserve the right to change this policy at any time.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the FaqCategoryModelV1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FaqCategoryModelV1{}

// FaqCategoryModelV1 struct for FaqCategoryModelV1
type FaqCategoryModelV1 struct {
	CategoryId int64   `json:"category_id"`
	Title      *string `json:"title,omitempty"`
	Position   *int64  `json:"position,omitempty"`
}

// NewFaqCategoryModelV1 instantiates a new FaqCategoryModelV1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFaqCategoryModelV1(categoryId int64) *FaqCategoryModelV1 {
	this := FaqCategoryModelV1{}
	this.CategoryId = categoryId
	return &this
}

// NewFaqCategoryModelV1WithDefaults instantiates a new FaqCategoryModelV1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFaqCategoryModelV1WithDefaults() *FaqCategoryModelV1 {
	this := FaqCategoryModelV1{}
	return &this
}

// GetCategoryId returns the CategoryId field value
func (o *FaqCategoryModelV1) GetCategoryId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.CategoryId
}

// GetCategoryIdOk returns a tuple with the CategoryId field value
// and a boolean to check if the value has been set.
func (o *FaqCategoryModelV1) GetCategoryIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CategoryId, true
}

// SetCategoryId sets field value
func (o *FaqCategoryModelV1) SetCategoryId(v int64) {
	o.CategoryId = v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *FaqCategoryModelV1) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FaqCategoryModelV1) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *FaqCategoryModelV1) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *FaqCategoryModelV1) SetTitle(v string) {
	o.Title = &v
}

// GetPosition returns the Position field value if set, zero value otherwise.
func (o *FaqCategoryModelV1) GetPosition() int64 {
	if o == nil || IsNil(o.Position) {
		var ret int64
		return ret
	}
	return *o.Position
}

// GetPositionOk returns a tuple with the Position field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FaqCategoryModelV1) GetPositionOk() (*int64, bool) {
	if o == nil || IsNil(o.Position) {
		return nil, false
	}
	return o.Position, true
}

// HasPosition returns a boolean if a field has been set.
func (o *FaqCategoryModelV1) HasPosition() bool {
	if o != nil && !IsNil(o.Position) {
		return true
	}

	return false
}

// SetPosition gets a reference to the given int64 and assigns it to the Position field.
func (o *FaqCategoryModelV1) SetPosition(v int64) {
	o.Position = &v
}

func (o FaqCategoryModelV1) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FaqCategoryModelV1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["category_id"] = o.CategoryId
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Position) {
		toSerialize["position"] = o.Position
	}
	return toSerialize, nil
}

type NullableFaqCategoryModelV1 struct {
	value *FaqCategoryModelV1
	isSet bool
}

func (v NullableFaqCategoryModelV1) Get() *FaqCategoryModelV1 {
	return v.value
}

func (v *NullableFaqCategoryModelV1) Set(val *FaqCategoryModelV1) {
	v.value = val
	v.isSet = true
}

func (v NullableFaqCategoryModelV1) IsSet() bool {
	return v.isSet
}

func (v *NullableFaqCategoryModelV1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFaqCategoryModelV1(val *FaqCategoryModelV1) *NullableFaqCategoryModelV1 {
	return &NullableFaqCategoryModelV1{value: val, isSet: true}
}

func (v NullableFaqCategoryModelV1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFaqCategoryModelV1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
