/*
MangaUpdates API

This API powers our website. Most API functions are public and do not require an account. For user-based functions, you must register an account. Currently, user registration must be done through our main website and is disabled via this API.  Download OpenAPI Specification: [openapi.yaml](openapi.yaml)  Please contact us at the following emails if you have questions:  * lambchopsil@mangaupdates.com * manick@mangaupdates.com  ## Warranties  MangaUpdates makes no warranties about service availability, correctness of the data, or anything else. The service is provided as is, and may change at any time.  ## Acceptable Use Policy  * You will credit MangaUpdates when using data provided by this API. * You will use reasonable spacing between requests so as not to overwhelm the MangaUpdates servers, and employ caching mechanisms when accessing data. * You will NOT use MangaUpdates data or API in a way that will:     * Deceive or defraud users     * Assist or perform an illegal action     * Create spam     * Damage the database  We reserve the right to change this policy at any time.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ConvoUserIgnoreModelV1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConvoUserIgnoreModelV1{}

// ConvoUserIgnoreModelV1 struct for ConvoUserIgnoreModelV1
type ConvoUserIgnoreModelV1 struct {
	UserIgnored *bool `json:"user_ignored,omitempty"`
}

// NewConvoUserIgnoreModelV1 instantiates a new ConvoUserIgnoreModelV1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConvoUserIgnoreModelV1() *ConvoUserIgnoreModelV1 {
	this := ConvoUserIgnoreModelV1{}
	return &this
}

// NewConvoUserIgnoreModelV1WithDefaults instantiates a new ConvoUserIgnoreModelV1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConvoUserIgnoreModelV1WithDefaults() *ConvoUserIgnoreModelV1 {
	this := ConvoUserIgnoreModelV1{}
	return &this
}

// GetUserIgnored returns the UserIgnored field value if set, zero value otherwise.
func (o *ConvoUserIgnoreModelV1) GetUserIgnored() bool {
	if o == nil || IsNil(o.UserIgnored) {
		var ret bool
		return ret
	}
	return *o.UserIgnored
}

// GetUserIgnoredOk returns a tuple with the UserIgnored field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConvoUserIgnoreModelV1) GetUserIgnoredOk() (*bool, bool) {
	if o == nil || IsNil(o.UserIgnored) {
		return nil, false
	}
	return o.UserIgnored, true
}

// HasUserIgnored returns a boolean if a field has been set.
func (o *ConvoUserIgnoreModelV1) HasUserIgnored() bool {
	if o != nil && !IsNil(o.UserIgnored) {
		return true
	}

	return false
}

// SetUserIgnored gets a reference to the given bool and assigns it to the UserIgnored field.
func (o *ConvoUserIgnoreModelV1) SetUserIgnored(v bool) {
	o.UserIgnored = &v
}

func (o ConvoUserIgnoreModelV1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConvoUserIgnoreModelV1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.UserIgnored) {
		toSerialize["user_ignored"] = o.UserIgnored
	}
	return toSerialize, nil
}

type NullableConvoUserIgnoreModelV1 struct {
	value *ConvoUserIgnoreModelV1
	isSet bool
}

func (v NullableConvoUserIgnoreModelV1) Get() *ConvoUserIgnoreModelV1 {
	return v.value
}

func (v *NullableConvoUserIgnoreModelV1) Set(val *ConvoUserIgnoreModelV1) {
	v.value = val
	v.isSet = true
}

func (v NullableConvoUserIgnoreModelV1) IsSet() bool {
	return v.isSet
}

func (v *NullableConvoUserIgnoreModelV1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConvoUserIgnoreModelV1(val *ConvoUserIgnoreModelV1) *NullableConvoUserIgnoreModelV1 {
	return &NullableConvoUserIgnoreModelV1{value: val, isSet: true}
}

func (v NullableConvoUserIgnoreModelV1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConvoUserIgnoreModelV1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


