/*
MangaUpdates API

This API powers our website. Most API functions are public and do not require an account. For user-based functions, you must register an account. Currently, user registration must be done through our main website and is disabled via this API.  Download OpenAPI Specification: [openapi.yaml](openapi.yaml)  Please contact us at the following emails if you have questions:  * lambchopsil@mangaupdates.com * manick@mangaupdates.com  ## Warranties  MangaUpdates makes no warranties about service availability, correctness of the data, or anything else. The service is provided as is, and may change at any time.  ## Acceptable Use Policy  * You will credit MangaUpdates when using data provided by this API. * You will use reasonable spacing between requests so as not to overwhelm the MangaUpdates servers, and employ caching mechanisms when accessing data. * You will NOT use MangaUpdates data or API in a way that will:     * Deceive or defraud users     * Assist or perform an illegal action     * Create spam     * Damage the database  We reserve the right to change this policy at any time.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ForumWarnModelPublicV1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ForumWarnModelPublicV1{}

// ForumWarnModelPublicV1 struct for ForumWarnModelPublicV1
type ForumWarnModelPublicV1 struct {
	TimeAdded *TimeV1 `json:"time_added,omitempty"`
	Level     int64   `json:"level"`
}

// NewForumWarnModelPublicV1 instantiates a new ForumWarnModelPublicV1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewForumWarnModelPublicV1(level int64) *ForumWarnModelPublicV1 {
	this := ForumWarnModelPublicV1{}
	this.Level = level
	return &this
}

// NewForumWarnModelPublicV1WithDefaults instantiates a new ForumWarnModelPublicV1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewForumWarnModelPublicV1WithDefaults() *ForumWarnModelPublicV1 {
	this := ForumWarnModelPublicV1{}
	return &this
}

// GetTimeAdded returns the TimeAdded field value if set, zero value otherwise.
func (o *ForumWarnModelPublicV1) GetTimeAdded() TimeV1 {
	if o == nil || IsNil(o.TimeAdded) {
		var ret TimeV1
		return ret
	}
	return *o.TimeAdded
}

// GetTimeAddedOk returns a tuple with the TimeAdded field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ForumWarnModelPublicV1) GetTimeAddedOk() (*TimeV1, bool) {
	if o == nil || IsNil(o.TimeAdded) {
		return nil, false
	}
	return o.TimeAdded, true
}

// HasTimeAdded returns a boolean if a field has been set.
func (o *ForumWarnModelPublicV1) HasTimeAdded() bool {
	if o != nil && !IsNil(o.TimeAdded) {
		return true
	}

	return false
}

// SetTimeAdded gets a reference to the given TimeV1 and assigns it to the TimeAdded field.
func (o *ForumWarnModelPublicV1) SetTimeAdded(v TimeV1) {
	o.TimeAdded = &v
}

// GetLevel returns the Level field value
func (o *ForumWarnModelPublicV1) GetLevel() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Level
}

// GetLevelOk returns a tuple with the Level field value
// and a boolean to check if the value has been set.
func (o *ForumWarnModelPublicV1) GetLevelOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Level, true
}

// SetLevel sets field value
func (o *ForumWarnModelPublicV1) SetLevel(v int64) {
	o.Level = v
}

func (o ForumWarnModelPublicV1) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ForumWarnModelPublicV1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TimeAdded) {
		toSerialize["time_added"] = o.TimeAdded
	}
	toSerialize["level"] = o.Level
	return toSerialize, nil
}

type NullableForumWarnModelPublicV1 struct {
	value *ForumWarnModelPublicV1
	isSet bool
}

func (v NullableForumWarnModelPublicV1) Get() *ForumWarnModelPublicV1 {
	return v.value
}

func (v *NullableForumWarnModelPublicV1) Set(val *ForumWarnModelPublicV1) {
	v.value = val
	v.isSet = true
}

func (v NullableForumWarnModelPublicV1) IsSet() bool {
	return v.isSet
}

func (v *NullableForumWarnModelPublicV1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableForumWarnModelPublicV1(val *ForumWarnModelPublicV1) *NullableForumWarnModelPublicV1 {
	return &NullableForumWarnModelPublicV1{value: val, isSet: true}
}

func (v NullableForumWarnModelPublicV1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableForumWarnModelPublicV1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
