/*
MangaUpdates API

This API powers our website. Most API functions are public and do not require an account. For user-based functions, you must register an account. Currently, user registration must be done through our main website and is disabled via this API.  Download OpenAPI Specification: [openapi.yaml](openapi.yaml)  Please contact us at the following emails if you have questions:  * lambchopsil@mangaupdates.com * manick@mangaupdates.com  ## Warranties  MangaUpdates makes no warranties about service availability, correctness of the data, or anything else. The service is provided as is, and may change at any time.  ## Acceptable Use Policy  * You will credit MangaUpdates when using data provided by this API. * You will use reasonable spacing between requests so as not to overwhelm the MangaUpdates servers, and employ caching mechanisms when accessing data. * You will NOT use MangaUpdates data or API in a way that will:     * Deceive or defraud users     * Assist or perform an illegal action     * Create spam     * Damage the database  We reserve the right to change this policy at any time.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the FaqCategoryQuestionsModelV1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FaqCategoryQuestionsModelV1{}

// FaqCategoryQuestionsModelV1 struct for FaqCategoryQuestionsModelV1
type FaqCategoryQuestionsModelV1 struct {
	CategoryId int64                    `json:"category_id"`
	Title      *string                  `json:"title,omitempty"`
	Questions  []FaqQuestionOnlyModelV1 `json:"questions,omitempty"`
	Position   *int64                   `json:"position,omitempty"`
}

// NewFaqCategoryQuestionsModelV1 instantiates a new FaqCategoryQuestionsModelV1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFaqCategoryQuestionsModelV1(categoryId int64) *FaqCategoryQuestionsModelV1 {
	this := FaqCategoryQuestionsModelV1{}
	this.CategoryId = categoryId
	return &this
}

// NewFaqCategoryQuestionsModelV1WithDefaults instantiates a new FaqCategoryQuestionsModelV1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFaqCategoryQuestionsModelV1WithDefaults() *FaqCategoryQuestionsModelV1 {
	this := FaqCategoryQuestionsModelV1{}
	return &this
}

// GetCategoryId returns the CategoryId field value
func (o *FaqCategoryQuestionsModelV1) GetCategoryId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.CategoryId
}

// GetCategoryIdOk returns a tuple with the CategoryId field value
// and a boolean to check if the value has been set.
func (o *FaqCategoryQuestionsModelV1) GetCategoryIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CategoryId, true
}

// SetCategoryId sets field value
func (o *FaqCategoryQuestionsModelV1) SetCategoryId(v int64) {
	o.CategoryId = v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *FaqCategoryQuestionsModelV1) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FaqCategoryQuestionsModelV1) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *FaqCategoryQuestionsModelV1) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *FaqCategoryQuestionsModelV1) SetTitle(v string) {
	o.Title = &v
}

// GetQuestions returns the Questions field value if set, zero value otherwise.
func (o *FaqCategoryQuestionsModelV1) GetQuestions() []FaqQuestionOnlyModelV1 {
	if o == nil || IsNil(o.Questions) {
		var ret []FaqQuestionOnlyModelV1
		return ret
	}
	return o.Questions
}

// GetQuestionsOk returns a tuple with the Questions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FaqCategoryQuestionsModelV1) GetQuestionsOk() ([]FaqQuestionOnlyModelV1, bool) {
	if o == nil || IsNil(o.Questions) {
		return nil, false
	}
	return o.Questions, true
}

// HasQuestions returns a boolean if a field has been set.
func (o *FaqCategoryQuestionsModelV1) HasQuestions() bool {
	if o != nil && !IsNil(o.Questions) {
		return true
	}

	return false
}

// SetQuestions gets a reference to the given []FaqQuestionOnlyModelV1 and assigns it to the Questions field.
func (o *FaqCategoryQuestionsModelV1) SetQuestions(v []FaqQuestionOnlyModelV1) {
	o.Questions = v
}

// GetPosition returns the Position field value if set, zero value otherwise.
func (o *FaqCategoryQuestionsModelV1) GetPosition() int64 {
	if o == nil || IsNil(o.Position) {
		var ret int64
		return ret
	}
	return *o.Position
}

// GetPositionOk returns a tuple with the Position field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FaqCategoryQuestionsModelV1) GetPositionOk() (*int64, bool) {
	if o == nil || IsNil(o.Position) {
		return nil, false
	}
	return o.Position, true
}

// HasPosition returns a boolean if a field has been set.
func (o *FaqCategoryQuestionsModelV1) HasPosition() bool {
	if o != nil && !IsNil(o.Position) {
		return true
	}

	return false
}

// SetPosition gets a reference to the given int64 and assigns it to the Position field.
func (o *FaqCategoryQuestionsModelV1) SetPosition(v int64) {
	o.Position = &v
}

func (o FaqCategoryQuestionsModelV1) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FaqCategoryQuestionsModelV1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["category_id"] = o.CategoryId
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Questions) {
		toSerialize["questions"] = o.Questions
	}
	if !IsNil(o.Position) {
		toSerialize["position"] = o.Position
	}
	return toSerialize, nil
}

type NullableFaqCategoryQuestionsModelV1 struct {
	value *FaqCategoryQuestionsModelV1
	isSet bool
}

func (v NullableFaqCategoryQuestionsModelV1) Get() *FaqCategoryQuestionsModelV1 {
	return v.value
}

func (v *NullableFaqCategoryQuestionsModelV1) Set(val *FaqCategoryQuestionsModelV1) {
	v.value = val
	v.isSet = true
}

func (v NullableFaqCategoryQuestionsModelV1) IsSet() bool {
	return v.isSet
}

func (v *NullableFaqCategoryQuestionsModelV1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFaqCategoryQuestionsModelV1(val *FaqCategoryQuestionsModelV1) *NullableFaqCategoryQuestionsModelV1 {
	return &NullableFaqCategoryQuestionsModelV1{value: val, isSet: true}
}

func (v NullableFaqCategoryQuestionsModelV1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFaqCategoryQuestionsModelV1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
