/*
MangaUpdates API

This API powers our website. Most API functions are public and do not require an account. For user-based functions, you must register an account. Currently, user registration must be done through our main website and is disabled via this API.  Download OpenAPI Specification: [openapi.yaml](openapi.yaml)  Please contact us at the following emails if you have questions:  * lambchopsil@mangaupdates.com * manick@mangaupdates.com  ## Warranties  MangaUpdates makes no warranties about service availability, correctness of the data, or anything else. The service is provided as is, and may change at any time.  ## Acceptable Use Policy  * You will credit MangaUpdates when using data provided by this API. * You will use reasonable spacing between requests so as not to overwhelm the MangaUpdates servers, and employ caching mechanisms when accessing data. * You will NOT use MangaUpdates data or API in a way that will:     * Deceive or defraud users     * Assist or perform an illegal action     * Create spam     * Damage the database  We reserve the right to change this policy at any time.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ForumPostModelSearchV1Topic type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ForumPostModelSearchV1Topic{}

// ForumPostModelSearchV1Topic struct for ForumPostModelSearchV1Topic
type ForumPostModelSearchV1Topic struct {
	ForumId *int64  `json:"forum_id,omitempty"`
	TopicId *int64  `json:"topic_id,omitempty"`
	Topic   *string `json:"topic,omitempty"`
}

// NewForumPostModelSearchV1Topic instantiates a new ForumPostModelSearchV1Topic object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewForumPostModelSearchV1Topic() *ForumPostModelSearchV1Topic {
	this := ForumPostModelSearchV1Topic{}
	return &this
}

// NewForumPostModelSearchV1TopicWithDefaults instantiates a new ForumPostModelSearchV1Topic object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewForumPostModelSearchV1TopicWithDefaults() *ForumPostModelSearchV1Topic {
	this := ForumPostModelSearchV1Topic{}
	return &this
}

// GetForumId returns the ForumId field value if set, zero value otherwise.
func (o *ForumPostModelSearchV1Topic) GetForumId() int64 {
	if o == nil || IsNil(o.ForumId) {
		var ret int64
		return ret
	}
	return *o.ForumId
}

// GetForumIdOk returns a tuple with the ForumId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ForumPostModelSearchV1Topic) GetForumIdOk() (*int64, bool) {
	if o == nil || IsNil(o.ForumId) {
		return nil, false
	}
	return o.ForumId, true
}

// HasForumId returns a boolean if a field has been set.
func (o *ForumPostModelSearchV1Topic) HasForumId() bool {
	if o != nil && !IsNil(o.ForumId) {
		return true
	}

	return false
}

// SetForumId gets a reference to the given int64 and assigns it to the ForumId field.
func (o *ForumPostModelSearchV1Topic) SetForumId(v int64) {
	o.ForumId = &v
}

// GetTopicId returns the TopicId field value if set, zero value otherwise.
func (o *ForumPostModelSearchV1Topic) GetTopicId() int64 {
	if o == nil || IsNil(o.TopicId) {
		var ret int64
		return ret
	}
	return *o.TopicId
}

// GetTopicIdOk returns a tuple with the TopicId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ForumPostModelSearchV1Topic) GetTopicIdOk() (*int64, bool) {
	if o == nil || IsNil(o.TopicId) {
		return nil, false
	}
	return o.TopicId, true
}

// HasTopicId returns a boolean if a field has been set.
func (o *ForumPostModelSearchV1Topic) HasTopicId() bool {
	if o != nil && !IsNil(o.TopicId) {
		return true
	}

	return false
}

// SetTopicId gets a reference to the given int64 and assigns it to the TopicId field.
func (o *ForumPostModelSearchV1Topic) SetTopicId(v int64) {
	o.TopicId = &v
}

// GetTopic returns the Topic field value if set, zero value otherwise.
func (o *ForumPostModelSearchV1Topic) GetTopic() string {
	if o == nil || IsNil(o.Topic) {
		var ret string
		return ret
	}
	return *o.Topic
}

// GetTopicOk returns a tuple with the Topic field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ForumPostModelSearchV1Topic) GetTopicOk() (*string, bool) {
	if o == nil || IsNil(o.Topic) {
		return nil, false
	}
	return o.Topic, true
}

// HasTopic returns a boolean if a field has been set.
func (o *ForumPostModelSearchV1Topic) HasTopic() bool {
	if o != nil && !IsNil(o.Topic) {
		return true
	}

	return false
}

// SetTopic gets a reference to the given string and assigns it to the Topic field.
func (o *ForumPostModelSearchV1Topic) SetTopic(v string) {
	o.Topic = &v
}

func (o ForumPostModelSearchV1Topic) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ForumPostModelSearchV1Topic) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ForumId) {
		toSerialize["forum_id"] = o.ForumId
	}
	if !IsNil(o.TopicId) {
		toSerialize["topic_id"] = o.TopicId
	}
	if !IsNil(o.Topic) {
		toSerialize["topic"] = o.Topic
	}
	return toSerialize, nil
}

type NullableForumPostModelSearchV1Topic struct {
	value *ForumPostModelSearchV1Topic
	isSet bool
}

func (v NullableForumPostModelSearchV1Topic) Get() *ForumPostModelSearchV1Topic {
	return v.value
}

func (v *NullableForumPostModelSearchV1Topic) Set(val *ForumPostModelSearchV1Topic) {
	v.value = val
	v.isSet = true
}

func (v NullableForumPostModelSearchV1Topic) IsSet() bool {
	return v.isSet
}

func (v *NullableForumPostModelSearchV1Topic) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableForumPostModelSearchV1Topic(val *ForumPostModelSearchV1Topic) *NullableForumPostModelSearchV1Topic {
	return &NullableForumPostModelSearchV1Topic{value: val, isSet: true}
}

func (v NullableForumPostModelSearchV1Topic) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableForumPostModelSearchV1Topic) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
