/*
MangaUpdates API

This API powers our website. Most API functions are public and do not require an account. For user-based functions, you must register an account. Currently, user registration must be done through our main website and is disabled via this API.  Download OpenAPI Specification: [openapi.yaml](openapi.yaml)  Please contact us at the following emails if you have questions:  * lambchopsil@mangaupdates.com * manick@mangaupdates.com  ## Warranties  MangaUpdates makes no warranties about service availability, correctness of the data, or anything else. The service is provided as is, and may change at any time.  ## Acceptable Use Policy  * You will credit MangaUpdates when using data provided by this API. * You will use reasonable spacing between requests so as not to overwhelm the MangaUpdates servers, and employ caching mechanisms when accessing data. * You will NOT use MangaUpdates data or API in a way that will:     * Deceive or defraud users     * Assist or perform an illegal action     * Create spam     * Damage the database  We reserve the right to change this policy at any time.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ListsPublicStatsModelV1Genres type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListsPublicStatsModelV1Genres{}

// ListsPublicStatsModelV1Genres struct for ListsPublicStatsModelV1Genres
type ListsPublicStatsModelV1Genres struct {
	GenreName *string `json:"genre_name,omitempty"`
	Count     *int64  `json:"count,omitempty"`
}

// NewListsPublicStatsModelV1Genres instantiates a new ListsPublicStatsModelV1Genres object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListsPublicStatsModelV1Genres() *ListsPublicStatsModelV1Genres {
	this := ListsPublicStatsModelV1Genres{}
	return &this
}

// NewListsPublicStatsModelV1GenresWithDefaults instantiates a new ListsPublicStatsModelV1Genres object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListsPublicStatsModelV1GenresWithDefaults() *ListsPublicStatsModelV1Genres {
	this := ListsPublicStatsModelV1Genres{}
	return &this
}

// GetGenreName returns the GenreName field value if set, zero value otherwise.
func (o *ListsPublicStatsModelV1Genres) GetGenreName() string {
	if o == nil || IsNil(o.GenreName) {
		var ret string
		return ret
	}
	return *o.GenreName
}

// GetGenreNameOk returns a tuple with the GenreName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListsPublicStatsModelV1Genres) GetGenreNameOk() (*string, bool) {
	if o == nil || IsNil(o.GenreName) {
		return nil, false
	}
	return o.GenreName, true
}

// HasGenreName returns a boolean if a field has been set.
func (o *ListsPublicStatsModelV1Genres) HasGenreName() bool {
	if o != nil && !IsNil(o.GenreName) {
		return true
	}

	return false
}

// SetGenreName gets a reference to the given string and assigns it to the GenreName field.
func (o *ListsPublicStatsModelV1Genres) SetGenreName(v string) {
	o.GenreName = &v
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *ListsPublicStatsModelV1Genres) GetCount() int64 {
	if o == nil || IsNil(o.Count) {
		var ret int64
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListsPublicStatsModelV1Genres) GetCountOk() (*int64, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *ListsPublicStatsModelV1Genres) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int64 and assigns it to the Count field.
func (o *ListsPublicStatsModelV1Genres) SetCount(v int64) {
	o.Count = &v
}

func (o ListsPublicStatsModelV1Genres) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListsPublicStatsModelV1Genres) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.GenreName) {
		toSerialize["genre_name"] = o.GenreName
	}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	return toSerialize, nil
}

type NullableListsPublicStatsModelV1Genres struct {
	value *ListsPublicStatsModelV1Genres
	isSet bool
}

func (v NullableListsPublicStatsModelV1Genres) Get() *ListsPublicStatsModelV1Genres {
	return v.value
}

func (v *NullableListsPublicStatsModelV1Genres) Set(val *ListsPublicStatsModelV1Genres) {
	v.value = val
	v.isSet = true
}

func (v NullableListsPublicStatsModelV1Genres) IsSet() bool {
	return v.isSet
}

func (v *NullableListsPublicStatsModelV1Genres) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListsPublicStatsModelV1Genres(val *ListsPublicStatsModelV1Genres) *NullableListsPublicStatsModelV1Genres {
	return &NullableListsPublicStatsModelV1Genres{value: val, isSet: true}
}

func (v NullableListsPublicStatsModelV1Genres) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListsPublicStatsModelV1Genres) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
