/*
MangaUpdates API

This API powers our website. Most API functions are public and do not require an account. For user-based functions, you must register an account. Currently, user registration must be done through our main website and is disabled via this API.  Download OpenAPI Specification: [openapi.yaml](openapi.yaml)  Please contact us at the following emails if you have questions:  * lambchopsil@mangaupdates.com * manick@mangaupdates.com  ## Warranties  MangaUpdates makes no warranties about service availability, correctness of the data, or anything else. The service is provided as is, and may change at any time.  ## Acceptable Use Policy  * You will credit MangaUpdates when using data provided by this API. * You will use reasonable spacing between requests so as not to overwhelm the MangaUpdates servers, and employ caching mechanisms when accessing data. * You will NOT use MangaUpdates data or API in a way that will:     * Deceive or defraud users     * Assist or perform an illegal action     * Create spam     * Damage the database  We reserve the right to change this policy at any time.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the UserGroupModelV1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserGroupModelV1{}

// UserGroupModelV1 struct for UserGroupModelV1
type UserGroupModelV1 struct {
	Id *string `json:"id,omitempty"`
	Name string `json:"name"`
	Description string `json:"description"`
}

// NewUserGroupModelV1 instantiates a new UserGroupModelV1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserGroupModelV1(name string, description string) *UserGroupModelV1 {
	this := UserGroupModelV1{}
	this.Name = name
	this.Description = description
	return &this
}

// NewUserGroupModelV1WithDefaults instantiates a new UserGroupModelV1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserGroupModelV1WithDefaults() *UserGroupModelV1 {
	this := UserGroupModelV1{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *UserGroupModelV1) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserGroupModelV1) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *UserGroupModelV1) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *UserGroupModelV1) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value
func (o *UserGroupModelV1) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *UserGroupModelV1) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *UserGroupModelV1) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
func (o *UserGroupModelV1) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *UserGroupModelV1) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *UserGroupModelV1) SetDescription(v string) {
	o.Description = v
}

func (o UserGroupModelV1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserGroupModelV1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	toSerialize["name"] = o.Name
	toSerialize["description"] = o.Description
	return toSerialize, nil
}

type NullableUserGroupModelV1 struct {
	value *UserGroupModelV1
	isSet bool
}

func (v NullableUserGroupModelV1) Get() *UserGroupModelV1 {
	return v.value
}

func (v *NullableUserGroupModelV1) Set(val *UserGroupModelV1) {
	v.value = val
	v.isSet = true
}

func (v NullableUserGroupModelV1) IsSet() bool {
	return v.isSet
}

func (v *NullableUserGroupModelV1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserGroupModelV1(val *UserGroupModelV1) *NullableUserGroupModelV1 {
	return &NullableUserGroupModelV1{value: val, isSet: true}
}

func (v NullableUserGroupModelV1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserGroupModelV1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


