/*
MangaUpdates API

This API powers our website. Most API functions are public and do not require an account. For user-based functions, you must register an account. Currently, user registration must be done through our main website and is disabled via this API.  Download OpenAPI Specification: [openapi.yaml](openapi.yaml)  Please contact us at the following emails if you have questions:  * lambchopsil@mangaupdates.com * manick@mangaupdates.com  ## Warranties  MangaUpdates makes no warranties about service availability, correctness of the data, or anything else. The service is provided as is, and may change at any time.  ## Acceptable Use Policy  * You will credit MangaUpdates when using data provided by this API. * You will use reasonable spacing between requests so as not to overwhelm the MangaUpdates servers, and employ caching mechanisms when accessing data. * You will NOT use MangaUpdates data or API in a way that will:     * Deceive or defraud users     * Assist or perform an illegal action     * Create spam     * Damage the database  We reserve the right to change this policy at any time.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ForumPostModelV1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ForumPostModelV1{}

// ForumPostModelV1 struct for ForumPostModelV1
type ForumPostModelV1 struct {
	PostId    *int64                    `json:"post_id,omitempty"`
	Body      *string                   `json:"body,omitempty"`
	Topic     *ForumPostModelV1Topic    `json:"topic,omitempty"`
	Author    *UserModelSearchV1        `json:"author,omitempty"`
	ReplyTo   *ForumPostModelV1ReplyTo  `json:"reply_to,omitempty"`
	LastEdit  *ForumPostModelV1LastEdit `json:"last_edit,omitempty"`
	TimeAdded *TimeV1                   `json:"time_added,omitempty"`
}

// NewForumPostModelV1 instantiates a new ForumPostModelV1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewForumPostModelV1() *ForumPostModelV1 {
	this := ForumPostModelV1{}
	return &this
}

// NewForumPostModelV1WithDefaults instantiates a new ForumPostModelV1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewForumPostModelV1WithDefaults() *ForumPostModelV1 {
	this := ForumPostModelV1{}
	return &this
}

// GetPostId returns the PostId field value if set, zero value otherwise.
func (o *ForumPostModelV1) GetPostId() int64 {
	if o == nil || IsNil(o.PostId) {
		var ret int64
		return ret
	}
	return *o.PostId
}

// GetPostIdOk returns a tuple with the PostId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ForumPostModelV1) GetPostIdOk() (*int64, bool) {
	if o == nil || IsNil(o.PostId) {
		return nil, false
	}
	return o.PostId, true
}

// HasPostId returns a boolean if a field has been set.
func (o *ForumPostModelV1) HasPostId() bool {
	if o != nil && !IsNil(o.PostId) {
		return true
	}

	return false
}

// SetPostId gets a reference to the given int64 and assigns it to the PostId field.
func (o *ForumPostModelV1) SetPostId(v int64) {
	o.PostId = &v
}

// GetBody returns the Body field value if set, zero value otherwise.
func (o *ForumPostModelV1) GetBody() string {
	if o == nil || IsNil(o.Body) {
		var ret string
		return ret
	}
	return *o.Body
}

// GetBodyOk returns a tuple with the Body field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ForumPostModelV1) GetBodyOk() (*string, bool) {
	if o == nil || IsNil(o.Body) {
		return nil, false
	}
	return o.Body, true
}

// HasBody returns a boolean if a field has been set.
func (o *ForumPostModelV1) HasBody() bool {
	if o != nil && !IsNil(o.Body) {
		return true
	}

	return false
}

// SetBody gets a reference to the given string and assigns it to the Body field.
func (o *ForumPostModelV1) SetBody(v string) {
	o.Body = &v
}

// GetTopic returns the Topic field value if set, zero value otherwise.
func (o *ForumPostModelV1) GetTopic() ForumPostModelV1Topic {
	if o == nil || IsNil(o.Topic) {
		var ret ForumPostModelV1Topic
		return ret
	}
	return *o.Topic
}

// GetTopicOk returns a tuple with the Topic field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ForumPostModelV1) GetTopicOk() (*ForumPostModelV1Topic, bool) {
	if o == nil || IsNil(o.Topic) {
		return nil, false
	}
	return o.Topic, true
}

// HasTopic returns a boolean if a field has been set.
func (o *ForumPostModelV1) HasTopic() bool {
	if o != nil && !IsNil(o.Topic) {
		return true
	}

	return false
}

// SetTopic gets a reference to the given ForumPostModelV1Topic and assigns it to the Topic field.
func (o *ForumPostModelV1) SetTopic(v ForumPostModelV1Topic) {
	o.Topic = &v
}

// GetAuthor returns the Author field value if set, zero value otherwise.
func (o *ForumPostModelV1) GetAuthor() UserModelSearchV1 {
	if o == nil || IsNil(o.Author) {
		var ret UserModelSearchV1
		return ret
	}
	return *o.Author
}

// GetAuthorOk returns a tuple with the Author field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ForumPostModelV1) GetAuthorOk() (*UserModelSearchV1, bool) {
	if o == nil || IsNil(o.Author) {
		return nil, false
	}
	return o.Author, true
}

// HasAuthor returns a boolean if a field has been set.
func (o *ForumPostModelV1) HasAuthor() bool {
	if o != nil && !IsNil(o.Author) {
		return true
	}

	return false
}

// SetAuthor gets a reference to the given UserModelSearchV1 and assigns it to the Author field.
func (o *ForumPostModelV1) SetAuthor(v UserModelSearchV1) {
	o.Author = &v
}

// GetReplyTo returns the ReplyTo field value if set, zero value otherwise.
func (o *ForumPostModelV1) GetReplyTo() ForumPostModelV1ReplyTo {
	if o == nil || IsNil(o.ReplyTo) {
		var ret ForumPostModelV1ReplyTo
		return ret
	}
	return *o.ReplyTo
}

// GetReplyToOk returns a tuple with the ReplyTo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ForumPostModelV1) GetReplyToOk() (*ForumPostModelV1ReplyTo, bool) {
	if o == nil || IsNil(o.ReplyTo) {
		return nil, false
	}
	return o.ReplyTo, true
}

// HasReplyTo returns a boolean if a field has been set.
func (o *ForumPostModelV1) HasReplyTo() bool {
	if o != nil && !IsNil(o.ReplyTo) {
		return true
	}

	return false
}

// SetReplyTo gets a reference to the given ForumPostModelV1ReplyTo and assigns it to the ReplyTo field.
func (o *ForumPostModelV1) SetReplyTo(v ForumPostModelV1ReplyTo) {
	o.ReplyTo = &v
}

// GetLastEdit returns the LastEdit field value if set, zero value otherwise.
func (o *ForumPostModelV1) GetLastEdit() ForumPostModelV1LastEdit {
	if o == nil || IsNil(o.LastEdit) {
		var ret ForumPostModelV1LastEdit
		return ret
	}
	return *o.LastEdit
}

// GetLastEditOk returns a tuple with the LastEdit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ForumPostModelV1) GetLastEditOk() (*ForumPostModelV1LastEdit, bool) {
	if o == nil || IsNil(o.LastEdit) {
		return nil, false
	}
	return o.LastEdit, true
}

// HasLastEdit returns a boolean if a field has been set.
func (o *ForumPostModelV1) HasLastEdit() bool {
	if o != nil && !IsNil(o.LastEdit) {
		return true
	}

	return false
}

// SetLastEdit gets a reference to the given ForumPostModelV1LastEdit and assigns it to the LastEdit field.
func (o *ForumPostModelV1) SetLastEdit(v ForumPostModelV1LastEdit) {
	o.LastEdit = &v
}

// GetTimeAdded returns the TimeAdded field value if set, zero value otherwise.
func (o *ForumPostModelV1) GetTimeAdded() TimeV1 {
	if o == nil || IsNil(o.TimeAdded) {
		var ret TimeV1
		return ret
	}
	return *o.TimeAdded
}

// GetTimeAddedOk returns a tuple with the TimeAdded field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ForumPostModelV1) GetTimeAddedOk() (*TimeV1, bool) {
	if o == nil || IsNil(o.TimeAdded) {
		return nil, false
	}
	return o.TimeAdded, true
}

// HasTimeAdded returns a boolean if a field has been set.
func (o *ForumPostModelV1) HasTimeAdded() bool {
	if o != nil && !IsNil(o.TimeAdded) {
		return true
	}

	return false
}

// SetTimeAdded gets a reference to the given TimeV1 and assigns it to the TimeAdded field.
func (o *ForumPostModelV1) SetTimeAdded(v TimeV1) {
	o.TimeAdded = &v
}

func (o ForumPostModelV1) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ForumPostModelV1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PostId) {
		toSerialize["post_id"] = o.PostId
	}
	if !IsNil(o.Body) {
		toSerialize["body"] = o.Body
	}
	if !IsNil(o.Topic) {
		toSerialize["topic"] = o.Topic
	}
	if !IsNil(o.Author) {
		toSerialize["author"] = o.Author
	}
	if !IsNil(o.ReplyTo) {
		toSerialize["reply_to"] = o.ReplyTo
	}
	if !IsNil(o.LastEdit) {
		toSerialize["last_edit"] = o.LastEdit
	}
	if !IsNil(o.TimeAdded) {
		toSerialize["time_added"] = o.TimeAdded
	}
	return toSerialize, nil
}

type NullableForumPostModelV1 struct {
	value *ForumPostModelV1
	isSet bool
}

func (v NullableForumPostModelV1) Get() *ForumPostModelV1 {
	return v.value
}

func (v *NullableForumPostModelV1) Set(val *ForumPostModelV1) {
	v.value = val
	v.isSet = true
}

func (v NullableForumPostModelV1) IsSet() bool {
	return v.isSet
}

func (v *NullableForumPostModelV1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableForumPostModelV1(val *ForumPostModelV1) *NullableForumPostModelV1 {
	return &NullableForumPostModelV1{value: val, isSet: true}
}

func (v NullableForumPostModelV1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableForumPostModelV1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
