/*
MangaUpdates API

This API powers our website. Most API functions are public and do not require an account. For user-based functions, you must register an account. Currently, user registration must be done through our main website and is disabled via this API.  Download OpenAPI Specification: [openapi.yaml](openapi.yaml)  Please contact us at the following emails if you have questions:  * lambchopsil@mangaupdates.com * manick@mangaupdates.com  ## Warranties  MangaUpdates makes no warranties about service availability, correctness of the data, or anything else. The service is provided as is, and may change at any time.  ## Acceptable Use Policy  * You will credit MangaUpdates when using data provided by this API. * You will use reasonable spacing between requests so as not to overwhelm the MangaUpdates servers, and employ caching mechanisms when accessing data. * You will NOT use MangaUpdates data or API in a way that will:     * Deceive or defraud users     * Assist or perform an illegal action     * Create spam     * Damage the database  We reserve the right to change this policy at any time.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AuthorsModelV1Social type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthorsModelV1Social{}

// AuthorsModelV1Social struct for AuthorsModelV1Social
type AuthorsModelV1Social struct {
	Officialsite *string `json:"officialsite,omitempty"`
	Facebook *string `json:"facebook,omitempty"`
	Twitter *string `json:"twitter,omitempty"`
}

// NewAuthorsModelV1Social instantiates a new AuthorsModelV1Social object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthorsModelV1Social() *AuthorsModelV1Social {
	this := AuthorsModelV1Social{}
	return &this
}

// NewAuthorsModelV1SocialWithDefaults instantiates a new AuthorsModelV1Social object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthorsModelV1SocialWithDefaults() *AuthorsModelV1Social {
	this := AuthorsModelV1Social{}
	return &this
}

// GetOfficialsite returns the Officialsite field value if set, zero value otherwise.
func (o *AuthorsModelV1Social) GetOfficialsite() string {
	if o == nil || IsNil(o.Officialsite) {
		var ret string
		return ret
	}
	return *o.Officialsite
}

// GetOfficialsiteOk returns a tuple with the Officialsite field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthorsModelV1Social) GetOfficialsiteOk() (*string, bool) {
	if o == nil || IsNil(o.Officialsite) {
		return nil, false
	}
	return o.Officialsite, true
}

// HasOfficialsite returns a boolean if a field has been set.
func (o *AuthorsModelV1Social) HasOfficialsite() bool {
	if o != nil && !IsNil(o.Officialsite) {
		return true
	}

	return false
}

// SetOfficialsite gets a reference to the given string and assigns it to the Officialsite field.
func (o *AuthorsModelV1Social) SetOfficialsite(v string) {
	o.Officialsite = &v
}

// GetFacebook returns the Facebook field value if set, zero value otherwise.
func (o *AuthorsModelV1Social) GetFacebook() string {
	if o == nil || IsNil(o.Facebook) {
		var ret string
		return ret
	}
	return *o.Facebook
}

// GetFacebookOk returns a tuple with the Facebook field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthorsModelV1Social) GetFacebookOk() (*string, bool) {
	if o == nil || IsNil(o.Facebook) {
		return nil, false
	}
	return o.Facebook, true
}

// HasFacebook returns a boolean if a field has been set.
func (o *AuthorsModelV1Social) HasFacebook() bool {
	if o != nil && !IsNil(o.Facebook) {
		return true
	}

	return false
}

// SetFacebook gets a reference to the given string and assigns it to the Facebook field.
func (o *AuthorsModelV1Social) SetFacebook(v string) {
	o.Facebook = &v
}

// GetTwitter returns the Twitter field value if set, zero value otherwise.
func (o *AuthorsModelV1Social) GetTwitter() string {
	if o == nil || IsNil(o.Twitter) {
		var ret string
		return ret
	}
	return *o.Twitter
}

// GetTwitterOk returns a tuple with the Twitter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthorsModelV1Social) GetTwitterOk() (*string, bool) {
	if o == nil || IsNil(o.Twitter) {
		return nil, false
	}
	return o.Twitter, true
}

// HasTwitter returns a boolean if a field has been set.
func (o *AuthorsModelV1Social) HasTwitter() bool {
	if o != nil && !IsNil(o.Twitter) {
		return true
	}

	return false
}

// SetTwitter gets a reference to the given string and assigns it to the Twitter field.
func (o *AuthorsModelV1Social) SetTwitter(v string) {
	o.Twitter = &v
}

func (o AuthorsModelV1Social) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthorsModelV1Social) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Officialsite) {
		toSerialize["officialsite"] = o.Officialsite
	}
	if !IsNil(o.Facebook) {
		toSerialize["facebook"] = o.Facebook
	}
	if !IsNil(o.Twitter) {
		toSerialize["twitter"] = o.Twitter
	}
	return toSerialize, nil
}

type NullableAuthorsModelV1Social struct {
	value *AuthorsModelV1Social
	isSet bool
}

func (v NullableAuthorsModelV1Social) Get() *AuthorsModelV1Social {
	return v.value
}

func (v *NullableAuthorsModelV1Social) Set(val *AuthorsModelV1Social) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthorsModelV1Social) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthorsModelV1Social) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthorsModelV1Social(val *AuthorsModelV1Social) *NullableAuthorsModelV1Social {
	return &NullableAuthorsModelV1Social{value: val, isSet: true}
}

func (v NullableAuthorsModelV1Social) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthorsModelV1Social) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


