/*
MangaUpdates API

This API powers our website. Most API functions are public and do not require an account. For user-based functions, you must register an account. Currently, user registration must be done through our main website and is disabled via this API.  Download OpenAPI Specification: [openapi.yaml](openapi.yaml)  Please contact us at the following emails if you have questions:  * lambchopsil@mangaupdates.com * manick@mangaupdates.com  ## Warranties  MangaUpdates makes no warranties about service availability, correctness of the data, or anything else. The service is provided as is, and may change at any time.  ## Acceptable Use Policy  * You will credit MangaUpdates when using data provided by this API. * You will use reasonable spacing between requests so as not to overwhelm the MangaUpdates servers, and employ caching mechanisms when accessing data. * You will NOT use MangaUpdates data or API in a way that will:     * Deceive or defraud users     * Assist or perform an illegal action     * Create spam     * Damage the database  We reserve the right to change this policy at any time.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AboutusUserModelUpdateV1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AboutusUserModelUpdateV1{}

// AboutusUserModelUpdateV1 struct for AboutusUserModelUpdateV1
type AboutusUserModelUpdateV1 struct {
	Username *string `json:"username,omitempty"`
}

// NewAboutusUserModelUpdateV1 instantiates a new AboutusUserModelUpdateV1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAboutusUserModelUpdateV1() *AboutusUserModelUpdateV1 {
	this := AboutusUserModelUpdateV1{}
	return &this
}

// NewAboutusUserModelUpdateV1WithDefaults instantiates a new AboutusUserModelUpdateV1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAboutusUserModelUpdateV1WithDefaults() *AboutusUserModelUpdateV1 {
	this := AboutusUserModelUpdateV1{}
	return &this
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *AboutusUserModelUpdateV1) GetUsername() string {
	if o == nil || IsNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AboutusUserModelUpdateV1) GetUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *AboutusUserModelUpdateV1) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *AboutusUserModelUpdateV1) SetUsername(v string) {
	o.Username = &v
}

func (o AboutusUserModelUpdateV1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AboutusUserModelUpdateV1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	return toSerialize, nil
}

type NullableAboutusUserModelUpdateV1 struct {
	value *AboutusUserModelUpdateV1
	isSet bool
}

func (v NullableAboutusUserModelUpdateV1) Get() *AboutusUserModelUpdateV1 {
	return v.value
}

func (v *NullableAboutusUserModelUpdateV1) Set(val *AboutusUserModelUpdateV1) {
	v.value = val
	v.isSet = true
}

func (v NullableAboutusUserModelUpdateV1) IsSet() bool {
	return v.isSet
}

func (v *NullableAboutusUserModelUpdateV1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAboutusUserModelUpdateV1(val *AboutusUserModelUpdateV1) *NullableAboutusUserModelUpdateV1 {
	return &NullableAboutusUserModelUpdateV1{value: val, isSet: true}
}

func (v NullableAboutusUserModelUpdateV1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAboutusUserModelUpdateV1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


