/*
MangaUpdates API

This API powers our website. Most API functions are public and do not require an account. For user-based functions, you must register an account. Currently, user registration must be done through our main website and is disabled via this API.  Download OpenAPI Specification: [openapi.yaml](openapi.yaml)  Please contact us at the following emails if you have questions:  * lambchopsil@mangaupdates.com * manick@mangaupdates.com  ## Warranties  MangaUpdates makes no warranties about service availability, correctness of the data, or anything else. The service is provided as is, and may change at any time.  ## Acceptable Use Policy  * You will credit MangaUpdates when using data provided by this API. * You will use reasonable spacing between requests so as not to overwhelm the MangaUpdates servers, and employ caching mechanisms when accessing data. * You will NOT use MangaUpdates data or API in a way that will:     * Deceive or defraud users     * Assist or perform an illegal action     * Create spam     * Damage the database  We reserve the right to change this policy at any time.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AboutusUserModelV1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AboutusUserModelV1{}

// AboutusUserModelV1 struct for AboutusUserModelV1
type AboutusUserModelV1 struct {
	EntryId  int64   `json:"entry_id"`
	Position *int64  `json:"position,omitempty"`
	Username *string `json:"username,omitempty"`
	UserId   *int64  `json:"user_id,omitempty"`
}

// NewAboutusUserModelV1 instantiates a new AboutusUserModelV1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAboutusUserModelV1(entryId int64) *AboutusUserModelV1 {
	this := AboutusUserModelV1{}
	this.EntryId = entryId
	return &this
}

// NewAboutusUserModelV1WithDefaults instantiates a new AboutusUserModelV1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAboutusUserModelV1WithDefaults() *AboutusUserModelV1 {
	this := AboutusUserModelV1{}
	return &this
}

// GetEntryId returns the EntryId field value
func (o *AboutusUserModelV1) GetEntryId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.EntryId
}

// GetEntryIdOk returns a tuple with the EntryId field value
// and a boolean to check if the value has been set.
func (o *AboutusUserModelV1) GetEntryIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EntryId, true
}

// SetEntryId sets field value
func (o *AboutusUserModelV1) SetEntryId(v int64) {
	o.EntryId = v
}

// GetPosition returns the Position field value if set, zero value otherwise.
func (o *AboutusUserModelV1) GetPosition() int64 {
	if o == nil || IsNil(o.Position) {
		var ret int64
		return ret
	}
	return *o.Position
}

// GetPositionOk returns a tuple with the Position field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AboutusUserModelV1) GetPositionOk() (*int64, bool) {
	if o == nil || IsNil(o.Position) {
		return nil, false
	}
	return o.Position, true
}

// HasPosition returns a boolean if a field has been set.
func (o *AboutusUserModelV1) HasPosition() bool {
	if o != nil && !IsNil(o.Position) {
		return true
	}

	return false
}

// SetPosition gets a reference to the given int64 and assigns it to the Position field.
func (o *AboutusUserModelV1) SetPosition(v int64) {
	o.Position = &v
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *AboutusUserModelV1) GetUsername() string {
	if o == nil || IsNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AboutusUserModelV1) GetUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *AboutusUserModelV1) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *AboutusUserModelV1) SetUsername(v string) {
	o.Username = &v
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *AboutusUserModelV1) GetUserId() int64 {
	if o == nil || IsNil(o.UserId) {
		var ret int64
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AboutusUserModelV1) GetUserIdOk() (*int64, bool) {
	if o == nil || IsNil(o.UserId) {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *AboutusUserModelV1) HasUserId() bool {
	if o != nil && !IsNil(o.UserId) {
		return true
	}

	return false
}

// SetUserId gets a reference to the given int64 and assigns it to the UserId field.
func (o *AboutusUserModelV1) SetUserId(v int64) {
	o.UserId = &v
}

func (o AboutusUserModelV1) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AboutusUserModelV1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["entry_id"] = o.EntryId
	if !IsNil(o.Position) {
		toSerialize["position"] = o.Position
	}
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	if !IsNil(o.UserId) {
		toSerialize["user_id"] = o.UserId
	}
	return toSerialize, nil
}

type NullableAboutusUserModelV1 struct {
	value *AboutusUserModelV1
	isSet bool
}

func (v NullableAboutusUserModelV1) Get() *AboutusUserModelV1 {
	return v.value
}

func (v *NullableAboutusUserModelV1) Set(val *AboutusUserModelV1) {
	v.value = val
	v.isSet = true
}

func (v NullableAboutusUserModelV1) IsSet() bool {
	return v.isSet
}

func (v *NullableAboutusUserModelV1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAboutusUserModelV1(val *AboutusUserModelV1) *NullableAboutusUserModelV1 {
	return &NullableAboutusUserModelV1{value: val, isSet: true}
}

func (v NullableAboutusUserModelV1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAboutusUserModelV1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
